query getAllFilms($after: String,
    $first: Int) {
    allFilms(after: $after, first: $first){
        totalCount
        edges {
            cursor
            node {
                id
            }
        }
        pageInfo {
            startCursor
            hasNextPage
            hasPreviousPage
            endCursor
        }
        films {
            title
            episodeID
            id
        }
    }
}

query getFilm($id: ID) {
    film(id: $id) {
        title
        episodeID
        openingCrawl
        director
        producers
        releaseDate
        speciesConnection{
            totalCount
            species {
                id
                name
            }
        }
        starshipConnection{
            totalCount
            starships {
                id
                name
            }
        }
        characterConnection{
            totalCount
            characters {
                id
                name
            }
        }
        planetConnection{
            totalCount
            planets {
                id
                name
            }
        }
        vehicleConnection{
            totalCount
            vehicles {
                id
                name
            }
        }
        created
        edited
        id
    }
}