query getAllPlanets($after: String,
    $first: Int) {
    allPlanets(after: $after, first: $first){
        totalCount
        edges {
            cursor
            node {
                id
            }
        }
        pageInfo {
            startCursor
            hasNextPage
            hasPreviousPage
            endCursor
        }
        planets {
            name
            population
            id
        }
    }
}

query getPlanet($id: ID) {
    planet(id: $id) {
        name
        diameter
        rotationPeriod
        orbitalPeriod
        gravity
        population
        climates
        terrains
        surfaceWater
        residentConnection{
            totalCount
            residents {
                id
                name
            }
        }
        filmConnection{
            totalCount
            films {
                id
                title
            }
        }
        created
        edited
        id
    }
}