image: eclipse-temurin:17-jdk-jammy

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_TOOLS: "9477386"
  PACKAGE_NAME: "com.anjo.starwarswikicompose"


before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip
  - export ANDROID_HOME="${PWD}/android-sdk-root"
  - install -d $ANDROID_HOME

  - wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
  - mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
  - sdkmanager --version

  #  use yes to accept all licenses
  - yes | sdkmanager --licenses > /dev/null || true
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, but just for surity
  - chmod +x ./gradlew

stages:
  - test
  - build
  - buildToDeploy

unitTest:
  stage: test
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  timeout: 20 minutes
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - echo "Run Unit tests"
    - ./gradlew testDebugUnitTest
  artifacts:
    name: 'SW_COMPOSE_UNIT_TEST_REPORT-$CI_PIPELINE_IID'
    expire_in: 30 days
    when: always
    reports:
      junit: [
        ./**/build/test-results/testDebugUnitTest/TEST-*.xml,
      ]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
build:
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  timeout: 20 minutes
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew assemble
    - echo "Publish artifact!"
  artifacts:
    name: 'SW_COMPOSE-$CI_PIPELINE_IID'
    paths:
      - /builds/jagieloadrian/starwarswikicompose/app/build/outputs/apk/debug/*.apk
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always


buildToDeploy:
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  timeout: 20 minutes
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew assembleRelease
    - echo "App assembled"
    - ./gradlew bundleRelease
    - echo "Created bundle file!"
    - ./gradlew playstorepublish:installDist
    - AAB_PATH=/builds/jagieloadrian/starwarswikicompose/app/build/outputs/bundle/release/StarWarsWikiCompose-release.aab
    - UPLOADER=/builds/jagieloadrian/starwarswikicompose/playstorepublish/build/install/playstorepublish/bin/playstorepublish
    - GOOGLE_PLAY_PRIVATE_KEY_JSON=/builds/jagieloadrian/starwarswikicompose/service-account.json
    - echo Deploying "${PACKAGE_NAME}" to Play Console, using "${AAB_PATH}"
    - chmod +x $UPLOADER
    - $UPLOADER $PACKAGE_NAME $AAB_PATH $GOOGLE_PLAY_PRIVATE_KEY_JSON
    - echo "Published artifact!"
  artifacts:
    name: 'SW_COMPOSE-$CI_PIPELINE_IID'
    paths:
      - /builds/jagieloadrian/starwarswikicompose/app/build/outputs/apk/release/*.apk
    expire_in: 30 days
  rules:
    - if: $executeManualJob == "true"
      when: always
    - when: never