image: eclipse-temurin:17-jdk-jammy

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_TOOLS:   "9477386"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip
  - apt-get install tree
  - export ANDROID_HOME="${PWD}/android-sdk-root"
  - install -d $ANDROID_HOME


  - wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
  - mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
  - sdkmanager --version

  # use yes to accept all licenses
  - yes | sdkmanager --licenses > /dev/null || true
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, but just for surity
  - chmod +x ./gradlew



stages:
  - build

assembleDebug:
  stage: build
  script:
    - tree /builds
    - ./gradlew build
    - echo "Publish artifact!"  
  artifacts:
    paths:
    - /builds/jagieloadrian/starwarswikicompose/*-.apk
    expire_in: 30 days