package com.anjo.starwarswikicompose.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp
val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp
val NAME_PLACEHOLDER_HEIGHT = 60.dp
val INFO_BOX_HEIGHT = 100.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp
val PICTURE_HEIGHT = 400.dp
val VEHICLE_PICTURE_HEIGHT = 260.dp
val TOP_APP_BAR_HEIGHT = 56.dp
val SMALL_BORDER = 2.dp
val SMALL_PADDING_FOR_INFOBOX = 4.dp
val TOP_BAR_HEIGHT = 40.dp
val HOME_ICON_HEIGHT = 32.dp
