plugins {
    id ("com.android.application")
    id ("org.jetbrains.kotlin.android")
    id ("com.google.devtools.ksp")
    id ("dagger.hilt.android.plugin")
    id ("org.jetbrains.kotlin.plugin.serialization") version "1.9.10"
    id ("com.apollographql.apollo3") version "3.8.2"
}

apollo {
    service("service") {
        packageName.set("com.anjo")
    }
}

android {
    namespace 'com.anjo.starwarswikicompose'
    compileSdk 34

    defaultConfig {
        applicationId "com.anjo.starwarswikicompose"
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName "1.0"
        setArchivesBaseName("StarWarsWikiCompose")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        def FLICKR_API_KEY = "FLICKR_API"
        def AUTHOR = "AUTHOR"
        def FEEDBACK_RECEIVER = "FEEDBACK_RECEIVER"
        def FEEDBACK_RECEIVER_PASSWORD = "FEEDBACK_RECEIVER_PASSWORD"
        release {

            buildConfigField "String", FLICKR_API_KEY, "\"81db1beedc5982add055aa7d83136276\""
            buildConfigField "String", AUTHOR, "\"d18\""
            buildConfigField "String", FEEDBACK_RECEIVER, "\"diether18.apps@gmail.com\""
            buildConfigField "String", FEEDBACK_RECEIVER_PASSWORD, "\"dummy thing\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", FLICKR_API_KEY, "\"81db1beedc5982add055aa7d83136276\""
            buildConfigField "String", AUTHOR, "\"d18\""
            buildConfigField "String", FEEDBACK_RECEIVER, "\"diether18.apps@gmail.com\""
            buildConfigField "String", FEEDBACK_RECEIVER_PASSWORD, "\"dummy thing\""
        }

    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.3'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
            excludes += '/META-INF/*'
        }
    }
}

dependencies {

    //Core and compose
    implementation ("androidx.core:core-ktx:1.12.0")
    implementation ("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
    implementation "androidx.compose.runtime:runtime-livedata:$compose_ui_version"

    implementation ("androidx.activity:activity-compose:1.8.1")
    implementation "androidx.compose.ui:ui:$compose_ui_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_ui_version"
    implementation "androidx.compose.material:material:$compose_ui_version"
    implementation ("androidx.core:core-splashscreen:1.1.0-alpha02")

    // System UI Controller - Accompanist
    implementation "com.google.accompanist:accompanist-systemuicontroller:$accompanist_version"
    implementation ("androidx.paging:paging-compose:3.3.0-alpha02")

    //test
    testImplementation ("junit:junit:4.13.2")
    androidTestImplementation ("androidx.test.ext:junit:1.1.5")
    androidTestImplementation ("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_ui_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_ui_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_ui_version"

    //apollo implementation
    implementation("com.apollographql.apollo3:apollo-runtime:3.8.2")
    implementation("com.apollographql.apollo3:apollo-api:3.8.2")
    implementation("com.apollographql.apollo3:apollo-normalized-cache:3.8.2")

    //Retrofit
    implementation ("com.squareup.retrofit2:retrofit:2.9.0")
    implementation ("com.squareup.retrofit2:converter-gson:2.9.0")
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0")

    //kotlinx serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")

    // Dagger - Hilt
    implementation "com.google.dagger:hilt-android:2.48.1"
    ksp ("com.google.dagger:hilt-android-compiler:2.48.1")
    ksp ("androidx.hilt:hilt-compiler:$hilt_compiler_version")

    // Compose - navigation
    implementation ("androidx.navigation:navigation-compose:2.7.5")
    implementation ("androidx.hilt:hilt-navigation-compose:$hilt_compiler_version")

    //Coil
    implementation("io.coil-kt:coil:2.4.0")
    implementation("io.coil-kt:coil-compose:2.4.0")

    //DataStore
    implementation("androidx.datastore:datastore-preferences:1.0.0")

    //Room
    implementation ("androidx.room:room-runtime:$room_version")
    ksp ("androidx.room:room-compiler:$room_version")
    implementation ("androidx.room:room-ktx:$room_version")

    //Mail
    implementation("com.sun.mail:jakarta.mail:2.0.1")

    //WorkManager
    implementation("androidx.work:work-runtime-ktx:2.8.1")
    implementation ("androidx.hilt:hilt-work:$hilt_compiler_version")

    //Permissions
    implementation("com.google.accompanist:accompanist-permissions:0.33.2-alpha")
}