package com.anjo.starwarswikicompose.utils

object TestTags {
    const val WELCOME_BUTTON_TAG = "welcome_button_tag"
    const val PROGRESS_INDICATOR_TAG = "ProgressIndicator"
    const val SHIMMER_EFFECT_TAG = "shimmer_effect_tag"
    const val FAB_MENU_TAG = "fabMenuTag"
    const val EDIT_FAB_BUTTON_TAG = "edit_fab_button_tag"
    const val RELATED_BUTTON_TAG = "related_button_tag"

    const val CUSTOM_ANIMATED_LABEL = "CustomContentAnimated"
    const val LOADING_ANIMATED_LABEL = "LoadingContentAnimated"
    const val ERROR_ANIMATED_LABEL = "ErrorContentAnimated"
    const val FAIL_ANIMATED_LABEL = "FailContentAnimated"
    const val SEARCH_BAR_CHUNKS_TAG = "searchBarChunksTag"

    const val SEARCH_CHUNK_ICON = "searchChunkIcon"
    const val CHUNK_LIST = "chunkList"
    const val STORMTROOPER_DRAW = "stormtrooperDraw"

    const val ADD_OBJECT_MAIN_SCREEN = "addObjectMainScreen"
    const val ADD_OBJECT_CATEGORY_DROPDOWN = "addObjectCategoryDropdown"
    const val ADD_OBJECT_PLANET_TAG = "addObjectPlanet"
    const val ADD_OBJECT_MOVIE_TAG = "addObjectMovie"
    const val ADD_OBJECT_SPECIE_TAG = "addObjectSpecie"
    const val ADD_OBJECT_STARSHIP_TAG = "addObjectStarship"
    const val ADD_OBJECT_VEHICLE_TAG = "addObjectVehicle"
    const val ADD_OBJECT_PERSON_TAG = "addObjectPerson"
    const val ADD_IMAGE_OBJECT_TAG = "addImageToObject"

    const val MAIN_NAV_GRAPH = "mainNavGraph"
    const val BANNER_BOX_TAG = "bannerBox"
    const val BOTTOM_APP_BAR = "bottomAppBar"
    const val TOP_APP_BAR_TAG = "topAppBar"
    const val CORNER_BUTTON_TAG = "cornerButton"
    const val SAVE_BUTTON_TAG = "saveButton"
    const val INFO_BOX_TAG = "infoBoxTag"
    const val INFO_BOX_CLICKABLE_TAG = "infoBoxClickableTag"
    const val INFO_BOX_COLUMN_TAG = "infoBoxColumnTag"
    const val RELATED_BOX_TAG = "relatedBoxTag"
    const val DOUBLE_BOX_TAG = "doubleBoxTag"
    const val TRIPLE_BOX_TAG = "tripleBoxTag"
    const val LOADING_BOX_TAG = "loadingBoxTag"
    const val LOADING_SCREEN_TAG = "loadingScreenTag"
    const val DETAIL_VISUAL_COMPONENT_TAG = "detailVisualComponentTag"
    const val EMPTY_CONTENT_TAG = "emptyContentTag"
    const val ERROR_CONTENT_TAG = "errorContentTag"
    const val FEEDBACK_CARD_TAG = "feedbackCardTag"
    const val INFORMATION_DIALOG_TAG = "informationDialogTag"
    const val INDICATOR_DOTS_TAG = "indicatorDotsTag"
    const val SEARCH_BAR_TAG = "searchBarTag"

    const val HOME_SCREEN_TAG = "homeScreenTag"
    const val HOME_CONTENT_SCREEN_TAG = "homeContentScreenTag"
    const val MOVIE_SCREEN_TAG = "movieScreenTag"
    const val PLANET_SCREEN_TAG = "planetScreenTag"
    const val STARSHIP_SCREEN_TAG = "starshipScreenTag"
    const val VEHICLE_SCREEN_TAG = "vehicleScreenTag"
    const val PERSON_SCREEN_TAG = "personScreenTag"
    const val SPECIE_SCREEN_TAG = "specieScreenTag"
    const val IMAGE_SCREEN_TAG = "imageScreenTag"
    const val IMAGES_CONTENT_TAG = "imagesContentTag"
    const val PHOTO_LIST_TAG = "photoListTag"
    const val FLICKR_IMAGE_BOX_TAG = "flickrImageBoxTag"
    const val WEBVIEW_SCREEN_TAG = "webviewScreenTag"
    const val WEB_VIEW_TAG = "webViewTag"

    const val COMMON_BUTTON_TAG = "commonButtonTag"
    const val UNIVERSAL_ROW_TEXT_TAG = "universalRowTextTag"
    const val UNIVERSAL_COLUMN_TEXT_TAG = "universalColumnTextTag"
    const val CONNECTION_TITLE_TAG = "connectionTitleTag"
    const val GALLERY_SLIDER_TAG = "gallerySliderTag"
    const val GALLERY_IMAGE_BOX_TAG = "galleryImageBoxTag"
    const val IMAGE_CAROUSEL_TAG = "imageCarouselTag"

    const val INFO_BOX_DIALOG_TAG = "infoBoxDialogTag"
    const val OPENING_CRAWL_DIALOG_TAG = "openingCrawlDialogTag"
    const val SHOW_MEME_TAG = "showMemeTag"
}