package com.anjo.starwarswikicompose.utils

object TestTags {
    const val WELCOME_BUTTON_TAG = "welcome_button_tag"
    const val PROGRESS_INDICATOR_TAG = "ProgressIndicator"
    const val SHIMMER_EFFECT_TAG = "shimmer_effect_tag"
    const val FAB_MENU_TAG = "fabMenuTag"
    const val EDIT_FAB_BUTTON_TAG = "edit_fab_button_tag"
    const val RELATED_BUTTON_TAG = "related_button_tag"

    const val CUSTOM_ANIMATED_LABEL = "CustomContentAnimated"
    const val LOADING_ANIMATED_LABEL = "LoadingContentAnimated"
    const val ERROR_ANIMATED_LABEL = "ErrorContentAnimated"
    const val FAIL_ANIMATED_LABEL = "FailContentAnimated"
    const val SEARCH_BAR_CHUNKS_TAG = "searchBarChunksTag"

    const val SEARCH_CHUNK_ICON = "searchChunkIcon"
    const val CHUNK_LIST = "chunkList"
    const val STORMTROOPER_DRAW = "stormtrooperDraw"

    const val ADD_OBJECT_MAIN_SCREEN = "addObjectMainScreen"
    const val ADD_OBJECT_CATEGORY_DROPDOWN = "addObjectCategoryDropdown"
    const val ADD_OBJECT_PLANET_TAG = "addObjectPlanet"
    const val ADD_OBJECT_MOVIE_TAG = "addObjectMovie"
    const val ADD_OBJECT_SPECIE_TAG = "addObjectSpecie"
    const val ADD_OBJECT_STARSHIP_TAG = "addObjectStarship"
    const val ADD_OBJECT_VEHICLE_TAG = "addObjectVehicle"
    const val ADD_OBJECT_PERSON_TAG = "addObjectPerson"
    const val ADD_IMAGE_OBJECT_TAG = "addImageToObject"

    const val MAIN_NAV_GRAPH = "mainNavGraph"
    const val BANNER_BOX_TAG = "bannerBox"
    const val BOTTOM_APP_BAR = "bottomAppBar"
    const val TOP_APP_BAR_TAG = "topAppBar"
    const val CORNER_BUTTON_TAG = "cornerButton"
    const val SAVE_BUTTON_TAG = "saveButton"
    const val INFO_BOX_TAG = "infoBoxTag"
    const val INFO_BOX_CLICKABLE_TAG = "infoBoxClickableTag"
    const val INFO_BOX_COLUMN_TAG = "infoBoxColumnTag"
    const val RELATED_BOX_TAG = "relatedBoxTag"
    const val DOUBLE_BOX_TAG = "doubleBoxTag"
    const val TRIPLE_BOX_TAG = "tripleBoxTag"
    const val LOADING_BOX_TAG = "loadingBoxTag"
    const val LOADING_SCREEN_TAG = "loadingScreenTag"
    const val DETAIL_VISUAL_COMPONENT_TAG = "detailVisualComponentTag"
    const val EMPTY_CONTENT_TAG = "emptyContentTag"
    const val ERROR_CONTENT_TAG = "errorContentTag"
    const val FEEDBACK_CARD_TAG = "feedbackCardTag"
    const val INFORMATION_DIALOG_TAG = "informationDialogTag"
    const val INDICATOR_DOTS_TAG = "indicatorDotsTag"
    const val SEARCH_BAR_TAG = "searchBarTag"
}